# Generated by Django 6.1.1 on 2026-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gradingcriteria_milestone_allocatedproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='research_area',
            field=models.CharField(choices=[('AI_ML', 'AI & Machine Learning'), ('CYBER', 'Cybersecurity & Blockchain'), ('IOT', 'IoT & Embedded Systems'), ('WEB', 'Web & Mobile Development'), ('DATA', 'Data Science & Analytics'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='research_area',
            field=models.CharField(choices=[('AI_ML', 'AI & Machine Learning'), ('CYBER', 'Cybersecurity & Blockchain'), ('IOT', 'IoT & Embedded Systems'), ('WEB', 'Web & Mobile Development'), ('DATA', 'Data Science & Analytics'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
