# Generated by Django 6.1.1 on 2026-09-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemsettings_alter_meetingslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, help_text='e.g. SCT211-0001/2021', max_length=20, null=True, unique=True),
        ),
    ]
