# Generated by Django 6.1.1 on 2026-09-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingslot',
            name='reschedule_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingslot',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='OPEN', max_length=10),
        ),
    ]
