# Generated by Django 6.1.1 on 2026-09-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_meetingslot_reschedule_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingbooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
