# Generated by Django 6.1.1 on 2026-09-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('BOOKING_CANCELLED', 'Booking Cancelled'), ('SLOT_COMPLETED', 'Slot Completed'), ('SLOT_RESCHEDULED', 'Slot Rescheduled'), ('SLOT CANCELLED', 'Slot Cancelled')], max_length=40),
        ),
    ]
