# Generated by Django 6.1.1 on 2026-09-28 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_notification_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectproposal',
            old_name='requested_supervisor',
            new_name='appointed_supervisor',
        ),
        migrations.AddField(
            model_name='milestone',
            name='has_chapters',
            field=models.BooleanField(default=False, help_text='Tick for the thesis milestone: students submit Chapters 1-5 separately'),
        ),
        migrations.AddField(
            model_name='notification',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.meetingslot'),
        ),
        migrations.AddField(
            model_name='submission',
            name='chapter',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 for chaptered milestones, empty otherwise', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('BOOKING_CANCELLED', 'Booking Cancelled'), ('SLOT_OPENED', 'Slot Opened'), ('SLOT_COMPLETED', 'Slot Completed'), ('SLOT_RESCHEDULED', 'Slot Rescheduled'), ('SLOT_CANCELLED', 'Slot Cancelled'), ('MEETING_REMINDER_24H', 'Meeting Reminder (24h)'), ('MEETING_REMINDER_1H', 'Meeting Reminder (1h)'), ('PROJECT_ALLOCATED', 'Project Allocated')], max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('project', 'milestone', 'chapter')},
        ),
        migrations.CreateModel(
            name='LoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=32, unique=True)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
