# Generated by Django 6.1.1 on 2026-10-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_requested_supervisor_projectproposal_appointed_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('BOOKING_CANCELLED', 'Booking Cancelled'), ('SLOT_OPENED', 'Slot Opened'), ('SLOT_COMPLETED', 'Slot Completed'), ('SLOT_RESCHEDULED', 'Slot Rescheduled'), ('SLOT_CANCELLED', 'Slot Cancelled'), ('MEETING_REMINDER_24H', 'Meeting Reminder (24h)'), ('MEETING_REMINDER_1H', 'Meeting Reminder (1h)'), ('PROJECT_ALLOCATED', 'Project Allocated'), ('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('PROPOSAL_APPROVED', 'Proposal Approved'), ('PROPOSAL_REJECTED', 'Proposal Rejected'), ('PROPOSAL_FEEDBACK', 'Proposal Feedback')], max_length=40),
        ),
    ]
